
version: 2
jobs:
    build:
        docker:
        - image: circleci/python:latest
        steps:
        - checkout
        - store_artifacts:
            path: /code/x2c0-games
            destination: up
        - run: 
            name: Install AWSCLI
            command: sudo pip install awscli
        - deploy:
            name: Deploy to S3 and create Cloudfront invalidation if tests pass and branch is Master
            command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
               aws s3 sync . s3://x2c0-games --delete && aws cloudfront create-invalidation --distribution-id E2FQWG2PEOZ63B  --paths "/*"
             else
               echo "Not master branch so not deploying"
             fi
